import gradio as gr
import pandas as pd
import numpy as np
import joblib

# 1. Load the structural deployment payload generated by your training script
payload = joblib.load("car_price_predictor.pkl")
model = payload['model']
expected_features = payload['features']

def predict_car_price(year, present_price, kms_driven, fuel_type, seller_type, transmission, owner):
    # Calculate dynamic asset age using the 2026 timeline reference anchor
    car_age = 2026 - year
    
    # Map raw user numerical entries into structural format
    input_data = {
        'Present_Price': [float(present_price)],
        'Kms_Driven': [int(kms_driven)],
        'Owner': [int(owner)],
        'Car_Age': [car_age]
    }
    
    input_df = pd.DataFrame(input_data)
    
    # 2. Dynamic One-Hot Encoding evaluation matches training schema layout
    input_df['Fuel_Type_Diesel'] = 1 if fuel_type == "Diesel" else 0
    input_df['Fuel_Type_Petrol'] = 1 if fuel_type == "Petrol" else 0
    input_df['Seller_Type_Individual'] = 1 if seller_type == "Individual" else 0
    input_df['Transmission_Manual'] = 1 if transmission == "Manual" else 0
    
    # Explicitly guarantee absolute feature signature vector alignment
    for col in expected_features:
        if col not in input_df.columns:
            input_df[col] = 0
            
    input_df = input_df[expected_features]
    
    # 3. Compute real-time regression evaluation values
    predicted_price = model.predict(input_df)[0]
    
    # Apply lower bound floor filter protecting against anomalous negative outputs safely
    final_val = max(0.0, float(predicted_price))
    
    return f"₹ {final_val:.2f} Lakhs"

# Create a professional, user-facing Gradio responsive application theme wrapper
demo = gr.Interface(
    fn=predict_car_price,
    inputs=[
        gr.Number(value=2018, label="Year of Purchase (e.g., 2014 - 2025)"),
        gr.Number(value=6.5, label="Original Showroom Price (In Lakhs)"),
        gr.Number(value=40000, label="Total Odometer Kilometers Driven"),
        gr.Dropdown(choices=["Petrol", "Diesel", "CNG"], value="Petrol", label="Fuel Engine Profile"),
        gr.Dropdown(choices=["Dealer", "Individual"], value="Dealer", label="Seller Classification"),
        gr.Dropdown(choices=["Manual", "Automatic"], value="Manual", label="Transmission Gear Mechanism"),
        gr.Slider(minimum=0, maximum=3, step=1, value=0, label="Number of Previous Owners")
    ],
    outputs=gr.Textbox(label="Estimated Resale Market Valuation"),
    title="🚗 Intelligent Car Price Valuation Engine",
    description="An end-to-end predictive intelligence interface utilizing optimized Random Forest Regressors with cross-validated hyperparameter adjustments to estimate vehicle resale evaluation bounds instantly."
)

if __name__ == "__main__":
    demo.launch()